version: '3.3'

services:

  newsletter-db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter

  api:
    image: zero2prod
    ports:
      - "8000:8000"
    depends_on:
      - newsletter-db
    environment:
      - APP_ENVIRONMENT=production
